name: Publish Docker

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  # Теперь мы заходим в GitHub Container Router, больше нет репо
                  registry: ghcr.io
                  # Username пользователя GitHub
                  username: ${{ github.actor }}
                  # Токен сгенерированный в гите, это не пароль!
                  password: ${{ secrets.DOCKER_GH_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ghcr.io/cptkokao/top-api:develop
